name: Philo_two macOS/Ubuntu compile check CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  jobuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: philo_two
      run:  |
            make re -C philo_two

  stevejobs:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: philo_two
      run:  |
            make re -C philo_two
